# Generated by Django 5.2.7 on 2025-10-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_tmdb_fields"),
        ("movies", "0003_migrate_genres_data"),
    ]

    operations = []
