# Generated by Django 5.2.7 on 2025-10-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_merge_0002_tmdb_fields_0003_migrate_genres_data"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="movie",
            new_name="movies_movi_tmdb_id_0e4cad_idx",
            old_name="movies_movi_tmdb_id_idx",
        ),
        migrations.RenameIndex(
            model_name="movie",
            new_name="movies_movi_imdb_id_d04af4_idx",
            old_name="movies_movi_imdb_id_idx",
        ),
    ]
