# Generated by Django 5.2.7 on 2025-10-16

from django.conf import settings
from django.db import migrations, models


def create_user_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_movies_movi_tmdb_id_idx_movies_movi_tmdb_id_0e4cad_idx_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_genre_update', models.DateTimeField(blank=True, null=True)),
                ('preferred_genres', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='movies.genre')),
                ('user', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_user_profiles, migrations.RunPython.noop),
    ]
